import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { getSession, getSessions, verifyLedger } from "../api.js";
import { pkr } from "./Worklist.jsx";

export default function Report() {
  const [id, setId] = useState("");
  const { data: sessions } = useQuery({ queryKey: ["sessions"], queryFn: getSessions });
  const { data: s } = useQuery({
    queryKey: ["session", Number(id)],
    queryFn: () => getSession(Number(id)),
    enabled: id !== "",
  });
  const { data: ledger } = useQuery({
    queryKey: ["ledger"],
    queryFn: verifyLedger,
    enabled: id !== "",
  });

  return (
    <section className="panel report">
      <div className="report-toolbar no-print">
        <h2>EOD Recon Report</h2>
        <select value={id} onChange={(e) => setId(e.target.value)}>
          <option value="">select session…</option>
          {(sessions ?? []).map((x) => (
            <option key={x.id} value={x.id}>
              #{x.id} — {x.teller_id} @ {x.branch_code} ({x.business_date})
            </option>
          ))}
        </select>
        {s && <button className="btn" onClick={() => window.print()}>Print</button>}
      </div>

      {s && (
        <article className="report-sheet">
          <header>
            <h1>ZeroBalance — EOD Reconciliation Report</h1>
            <p>
              Branch {s.branch_code} · Teller {s.teller_id} · {s.business_date} ·
              status: {s.status}
            </p>
          </header>

          <h3>Cash position</h3>
          <table className="table">
            <tbody>
              <tr><td>System cash (CBS)</td><td className="num">{pkr(s.system_cash)} PKR</td></tr>
              <tr><td>Counted cash (EOD count)</td><td className="num">{pkr(s.counted_cash)} PKR</td></tr>
              <tr className={s.variance !== 0 ? "variance" : ""}>
                <td>Variance</td><td className="num">{pkr(s.variance)} PKR</td>
              </tr>
              <tr><td>Transactions</td><td className="num">{s.txn_count}</td></tr>
            </tbody>
          </table>

          <h3>Denomination count (single EOD entry)</h3>
          <table className="table">
            <thead><tr><th>Denomination</th><th className="num">Notes</th><th className="num">Value (PKR)</th></tr></thead>
            <tbody>
              {Object.entries(s.denomination_count)
                .sort((a, b) => b[0] - a[0])
                .map(([d, n]) => (
                  <tr key={d}>
                    <td>{Number(d).toLocaleString("en-PK")}</td>
                    <td className="num">{n}</td>
                    <td className="num">{pkr(d * n)}</td>
                  </tr>
                ))}
            </tbody>
          </table>

          <h3>Engine findings (deterministic, top {s.suspects.length})</h3>
          {s.suspects.length === 0 && <p>No exceptions — till balanced.</p>}
          {s.suspects.map((x) => (
            <div className="report-suspect" key={x.rank}>
              <p>
                <strong>#{x.rank} {x.signature.replaceAll("_", " ")}</strong>
                {" — "}{x.txn_refs.join(", ") || "till count"} · {pkr(x.cash_delta)} PKR
              </p>
              {x.explanation_ur && (
                <p className="urdu" dir="rtl" lang="ur">{x.explanation_ur}</p>
              )}
            </div>
          ))}

          <footer>
            <p className="hash">
              Audit ledger: {ledger?.ok ? "chain verified ✓" : "VERIFY FAILED ✗"} ·
              head {ledger?.head?.slice(0, 16)}… · {ledger?.entries} entries
            </p>
            <p className="muted">
              Generated by ZeroBalance. Engine ranking is rule-based and reproducible;
              Urdu explanations are post-hoc (Groq) and carry no decision weight.
            </p>
          </footer>
        </article>
      )}
      {!s && <p className="muted">Select a session to render its report.</p>}
    </section>
  );
}
